### ISSUE TITLE
Migrating SVF to LLVM 4

### ISSUE THREAD

**Issue by jcarlson23** [unsw-corg/SVF#14]
Hello,

I am very new to SVF and somewhat naively I took a quick spin in the 3.8 LLVM code base (as shipped so to speak), and liking the code base, and capabilities, I then started towards migrating SVF towards the LLVM 4.0 release.  Perhaps not unsurprisingly I ran into a few problems, but primarily and this was one of the things that attracted me to SVF, the GraphTraits in 4.0 looks like it has some changes that are marked as a fixme:

  typedef typename GTraits::NodeRef           NodeRef;
  typedef typename GTraits::nodes_iterator    node_iterator;
  typedef typename GTraits::ChildIteratorType child_iterator;
  DOTTraits DTraits;

  static_assert(std::is_pointer<NodeRef>::value,
                "FIXME: Currently GraphWriter requires the NodeRef type to be "
                "a pointer.\nThe pointer usage should be moved to "
                "DOTGraphTraits, and removed from GraphWriter itself.”);

(that’s in the GraphWriter.h from LLVM 4.0 release).

So, is there anywhere, a paper perhaps, that you could refer me towards for understanding some of the details as well as the high level implementation of the graphing algorithms being used?  I come from a numerical background so I’m used to sparse solvers such as GMRES, etc, but the LLVM implementation (while I’m somewhat familiar with a few parts of LLVM) is somewhat new to me - I’ve generally re-used the SCC and other graph related algorithms without needing to dive in headfirst - that said, that looks like it’s on tap for my weekend :)

Another question I had was in the Memory separation capabilities, does this require disjoint regions?  It seems to read as if “no”?  But then that does limit any typical Formal Methods applications where analysis (that I’ve seen at least) typically requires disjoint regions.  For example I’ve seen several FM related LLVM papers replacing PHI nodes with simplifications.

Thanks!

**Comment by rockysui** [comment]
Hi Jared,

Thanks for your questions. 

1) On LLVM's GraphTraits
Type traits is a good C++ feature for graph traversal. As SVF uses graph traversal frequently, LLVM's GraphTraits is a perfect fit for our purpose.

The original graph traits idea came from boost library:
http://www.boost.org/doc/libs/1_46_1/libs/graph/doc/graph_traits.html
http://stackoverflow.com/questions/3979766/how-do-traits-classes-work
http://www.drdobbs.com/cpp/c-type-traits/184404270
or feel free to search some others reference.

To correctly use LLVM's GraphTraits, first you need to write a graph representation (e.g., PAG) based on a generic graph ("MemoryModel/GenericGraph.h"). Then you need to instantiate a GraphTraits for the graph. Please refer to lines 640-654 in "MemoryModel/PAG.h". Finally, you have to specify iterators (lines 181-235 in "MemoryModel/GenericGraph.h") to be used by different graph clients, such as GraphWriter in "Util/GraphUtil.h" and SCC in "include/Util/SCC.h".

2) On graph algorithms in SVF
SVF abstracts LLVM IR into various higher level graph representations, on which we have implemented a few classic algorithms, e.g., SCC (include/Util/SCC.h). They are implemented based on papers (e.g., "On finding the strongly connected components in a directed graph") as specified in our C++ header files.

3) On disjoint memory regions
Do you refer to our memory region partitioning algorithms in "MSSA/MemRegion.h" and "MSSA/MemPartition.h"? 

We have several options for memory region partitioning. Disjoint partitioning is one of them. You may wish to refer to our TSE 2014 paper (Section 4.2.2). For pointer analysis and/or dependence analysis, other partitioning strategies can also be applied to trade precision for efficiency, or the other way around.

Hopefully the above answers your questions. Good luck!

**Comment by rockysui** [comment]
Hi Jared,

Would you mind give a pull request once you finish the migration? We can start testing the correctness and performance from then.

Migrating SVF to LLVM 4.0 would help other users too.

Thanks!

**Comment by jcarlson23** [comment]
Hi Yulei,

Let me digest your above answers a bit (thank you for the details!) but in terms of the latter, of course, happy to give a pull request.  One of my motivations is to hopefully to extend some formal proof capabilities, hence my question on disjointness, and on that yes, I was referring to the memory region partitioning in MSSA - I haven't looked at all the options, I thought that migrating to 4.0 was both a useful exercise to touching a large, or significant, part of the code base and getting familiar while helping...

**Comment by jcarlson23** [comment]
Thanks again for comments Yulei.  I can see most of what I was concerned about is easily fixed.  Most of the instantiations become something along the line of:

`template<> struct GraphTraits<PTACallGraph*> : public GraphTraits<GenericGraph<PTACallGraphNode,PTACallGraphEdge>* > {
  typedef PTACallGraphNode *NodeRef;
};`

Where the NodeRef is required and I just need to dig up the right type to pass back.  It does looks to me like this might be unnecessary later if the NodeRef requirement drops but for 4.0 that doesn't seem to be the case.  There are some other API changes but making my way through them...

**Comment by jcarlson23** [comment]
Ah, think I figured this out...

**Comment by rockysui** [comment]
Good!

**Comment by jcarlson23** [comment]
Alright, some products starting to compile, but linkage errors indicate that perhaps some virtual functions aren't implemented (so new methods to 4.0 classes) and running those down is my next step.  Get started on that tomorrow or Monday...

**Comment by jcarlson23** [comment]
Confirmed the linkage issue.  The CMakeFiles look good at a first glance but compiling by hand worked (so just typing it in).  Likely my environment, or a Mac issue.  So I'll put around with this today/tomorrow and see where I am, perhaps comparing to a clean build on a linux VM (seems like a good check).  Anyway, confirmed the good news regarding the compilation, as I'm getting some delis with some intervention.

**Comment by jcarlson23** [comment]
Alright everything builds with llvm-4.  I need to get go over my changes one last time and then I can issue a PR with some notes for what I hope is a relatively painless merge.

**Comment by rockysui** [comment]
Hi Jared,

Thanks a lot for your efforts!

Yes, please make some notes for important updates. 
We will take a look at your patches and give you feedback later.
