### ISSUE TITLE
Merging in SUPA implementation?

### ISSUE THREAD

**Issue by dtzWill** [unsw-corg/SVF#20]
Don't mean to nag, but just a reminder that merging in SUPA implementation would be great and much appreciated! :+1:

The [SUPA website](http://www.cse.unsw.edu.au/~corg/supa/) suggests it's on your TODO, and idea when that will happen? Or is there anything blocking the effort that perhaps folks (such as myself) could help with?

Thanks!

**Comment by rockysui** [comment]
SUPA will not be merged at this stage. It involves a company IP. We will see how it goes before merging it. You may keep it for private use now.

**Comment by dtzWill** [comment]
Okay, thanks and appreciate the explanation and quick response! Have a good one! :)
