### ISSUE TITLE
Wiki documentation seems out of sync

### ISSUE THREAD

**Issue by roachspray** [unsw-corg/SVF#30]
The two wiki pages that describe using SVF to write
- flow and field insensitive analysis and
- a source/sink analyzer

seem to be out of sync with some of the code. I am guessing there will be no further updates, is this the case? If I could figure out what's what, I would be glad to contribute back.

**Comment by rockysui** [comment]
The pages might be a bit old. Of course, welcome to any contribution. I have set the wiki pages of SVF to be added/updated by any GitHub users.

Thanks!

**Comment by roachspray** [comment]
Ok thank you! I will edit as I go.
