### ISSUE TITLE
cmake build support (required for use with LLVM newer than 3.8 release)

### ISSUE THREAD

**Issue by dtzWill** [unsw-corg/SVF#5]
LLVM deprecated autoconf in favor of CMake around the 3.8 release, which means projects must move to CMake in order to be used with newer versions of LLVM.

Mostly filing issue to track the status of CMake support in SVF :).

Any plans on adding it in order to support continued use with LLVM?

**Comment by rockysui** [comment]
SVF was initially developed based on earlier version of LLVM (version 3.2) in which autoconf is still popular. Yes, we have to use CMake later as autoconf will be dropped in 3.8.1.  

Are you willing to help us make this change? or do you have some samples on how to set up a tiny cmake project using llvm libraries.

**Comment by dtzWill** [comment]
Understood.  I'm not sure--I've integrated it with my own cmake-based project but I'm not sure how to best accommodate your projects needs.  In particular, many of your components are built as both static libraries as well as loadable modules (for use in opt), and I'm not sure how to best accomplish that with CMake.

In my own project I only build SVF as static libraries that I link into my tools... if this is sufficient I'd be happy to share my CMake pieces, they're pretty simple :).

(Why was this closed?)

**Comment by rockysui** [comment]
Hi Will,

If possible, could you please send us a patch diff file on top of current SVF repo for CMake build? We could start from there.

Thanks
