### ISSUE TITLE
AndersenLCD implementation "incomplete": documentation and efficiency

### ISSUE THREAD

**Issue by dtzWill** [unsw-corg/SVF#6]
The implementation of lazy cycle detection is [described as 'incomplete' in Andersen.h](https://github.com/unsw-corg/SVF/blob/8ef26adf7d500bec03d241030fc1157c7757a85f/include/WPA/Andersen.h#L389),
is the implemented approach documented somewhere?

If not, could this be documented?

I suppose I'm unsure in what way what's implemented is "lazy cycle detection", is it?

**Comment by rockysui** [comment]
Our default Andersen's analysis uses wave propagation solver "AndersenWaveDiff" which has been extensively tested using our micro-benchmarks and many standard benchmarks CPU2000/2006. 

AndersenLCD is very simple implementation of lazy cycle detection algorithm. The implementation may not be well tuned and tested to match the performance proposed in its paper.  Feel free to improve it:)
